Repository nextcloud/forms, pull requests merged in 2020-07, with the labels that each got.

#485 Fix questions & submissions assignment
  src/views/Results.vue
Labels: 3. to review, bug, feature: 📊 responses & statistics

#460 Add summary response visualization, fix #314
  src/components/Results/Summary.vue
  src/views/Results.vue
Labels: 4. to release, design, enhancement, feature: 📊 responses & statistics, priority

#508 Move to webpack vue global config & clean routes
  appinfo/routes.php
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/components/Results/Submission.vue
  src/components/Results/Summary.vue
  src/views/Create.vue
  webpack.common.js
  webpack.dev.js
  webpack.js
  webpack.prod.js
Labels: 3. to review, enhancement

#513 Add screenshot of response visualization, adjust readme
  README.md
  appinfo/info.xml
  screenshots/forms3.png
Labels: 3. to review, design, enhancement

#484 Revert "Allow navigation through edit via Tab-Key"
  src/components/Questions/Question.vue
  src/components/Questions/QuestionMultiple.vue
Labels: 3. to review, bug, high, regression

#517 Fix actions
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: 3. to review, integration

#520 Fix dropdown submission insert
  lib/Controller/ApiController.php
  src/components/Questions/QuestionDropdown.vue
  src/views/Submit.vue
Labels: 2-feedback, 3. to review, bug, feature: 📝 submitting responses, high

#528 Fix substring utf8
  lib/Migration/Version010200Date20200323141300.php
Labels: 3. to review, bug

#533 Increase description length
  lib/Controller/PageController.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version020002Date20200729205932.php
Labels: 3. to review, enhancement, feature: 📑 form creation
