Repository nextcloud/forms, pull requests merged in 2020-05, with the labels that each got.

#325 Design fixes for submission view
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionShort.vue
  src/views/Submit.vue
Labels: 3. to review, bug, design, feature: submitting responses

#327 Prevent letter debounce erasing when creating new answers
  src/components/Questions/AnswerInput.vue
Labels: 2-feedback, 3. to review, bug, feature: form creation

#328 Move "Add a question" button to bottom
  src/components/Questions/Question.vue
  src/views/Create.vue
Labels: 3. to review, bug, design

#329 Fix multiple choice icon to make obvious it’s radio buttons
  css/icons.scss
  img/answer-multiple.svg
  img/expired-unvoted-vote.svg
  img/expired-voted-vote.svg
  img/maybe-toggle.svg
  img/maybe-vote-bordered.svg
  img/maybe-vote-variant.svg
  img/maybe-vote.svg
  img/no-comment.svg
  img/no-toggle.svg
  img/no-vote-bordered.svg
  img/no-vote.svg
  img/open-unvoted-vote.svg
  img/open-voted-vote.svg
  img/questionmark.svg
  img/save.svg
  img/toggle.svg
  img/unvoted-vote-bordered.svg
  img/yes-comment.svg
  img/yes-toggle.svg
  img/yes-vote-bordered.svg
  img/yes-vote.svg
Labels: 3. to review, design, enhancement, feature: form creation

#326 Fix expiration display
  src/components/AppNavigationForm.vue
  src/views/Sidebar.vue
  webpack.common.js
Labels: 3. to review, bug, design, feature: sharing settings

#338 Provide DBs max string lengths as InitialState
  lib/Controller/PageController.php
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, bug, feature: form creation

#315 Add title on public page
  css/flex.scss
  css/icons.scss
  css/main.scss
  css/public.scss
  css/submit.scss
  lib/Controller/PageController.php
Labels: 4. to release, bug, design

#345 Fix Submission Access
  lib/Controller/ApiController.php
Labels: 3. to review, bug

#341 New Result View
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Db/SubmissionMapper.php
  src/components/Results/Answer.vue
  src/components/Results/Submission.vue
  src/components/TopBar.vue
  src/components/resultItem.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review, enhancement, feature: responses & statistics

#347 Mandatory option on questions
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/views/Create.vue
  src/views/Submit.vue
Labels: 4. to release, enhancement

#351 Revert topbar changes
  src/components/TopBar.vue
  src/views/Create.vue
Labels: 3. to review, bug, design

#346 Fix users & groups sharing
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Controller/SystemController.php
  lib/Service/FormsService.php
  src/Forms.vue
  src/components/ShareDiv.vue
  src/components/UserDiv.vue
  src/components/shareDiv.vue
  src/mixins/ShareTypes.js
  src/views/Sidebar.vue
Labels: 3. to review, bug, enhancement, feature: sharing settings, high

#360 Fix Error-Messages
  src/views/Results.vue
Labels: 3. to review, bug

#362 Fix export-button
  src/views/Results.vue
Labels: 3. to review, bug, design

#363 Include more sharing links
  package-lock.json
  package.json
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/EmptyContent.vue
  src/views/Results.vue
  src/views/Sidebar.vue
Labels: 3. to review, bug, feature: sharing settings

#370 Set max-version to 20 for new development version of Nextcloud
  appinfo/info.xml
Labels: 3. to review, bug

#368 Update window title
  src/mixins/WindowTitleMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review, bug

#366 Fix overlapping text of long answers
  src/components/Questions/QuestionMultiple.vue
  src/views/Submit.vue
Labels: 3. to review, bug, design, feature: form creation, feature: submitting responses, high

#369 Focus title after form load
  src/views/Create.vue
Labels: 3. to review, design, enhancement, feature: form creation

#367 Do not prefill form or question title for less confusion
  lib/Controller/ApiController.php
  src/components/AppNavigationForm.vue
  src/components/Questions/Question.vue
  src/components/Results/Submission.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review, bug, design, feature: form creation

#376 Fix Results initalState missing
  lib/Controller/PageController.php
Labels: 3. to review, bug

#375 Correct fix window title
  src/utils/SetWindowTitle.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review, bug

#377 Fix redirects
  src/Forms.vue
  src/router.js
  src/views/Results.vue
Labels: 3. to review, bug

#387 Fix newQuestions console error mandatory null
  lib/Controller/ApiController.php
Labels: 3. to review, bug

#402 Sort Navigation newest forms first
  lib/Db/FormMapper.php
  src/Forms.vue
Labels: 3. to review, enhancement

#390 Fix todo comments
  lib/Controller/PageController.php
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionShort.vue
Labels: 3. to review, enhancement

#397 Fix remove empty questions on submit
  src/views/Submit.vue
Labels: 3. to review, bug, feature: 📑 form creation

#396 Fix saving options on fast proceed
  src/components/Questions/AnswerInput.vue
Labels: 3. to review, bug, feature: 📑 form creation

#392 Fix key-exists error
  lib/Controller/ApiController.php
Labels: 3. to review, bug, feature: 📑 form creation

#380 Close navigation on mobile on new form
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/EmptyContent.vue
Labels: 3. to review, bug, feature: 📑 form creation, pending fix

#404 Prevent question menu icon and menu itself overlapping top right actions
  src/components/TopBar.vue
Labels: 3. to review, bug, design, feature: 📑 form creation

#379 Fix Navigation active on results
  src/components/AppNavigationForm.vue
  src/router.js
Labels: 3. to review, bug, feature: 📊 responses & statistics

#410 Adjust cut descenders on formtitle
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, bug, design, feature: 📑 form creation, feature: 📝 submitting responses

#411 Change to vue classes
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, integration

#412 Add favicons
  appinfo/info.xml
  img/answer-checkbox.svg
  img/answer-multiple.svg
  img/app.svg
  img/drag-handle.svg
  img/favicon-mask.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
  img/forms.svg
  img/share.svg
Labels: 3. to review, design, enhancement

#414 Fix expiration editable
  src/views/Sidebar.vue
Labels: 3. to review, bug, feature: 👥 sharing settings

#417 Add a nice readme! :)
  README.md
  appinfo/info.xml
  img/screenshots/forms1.png
  img/screenshots/forms2.png
Labels: 3. to review, design, enhancement

#393 Use cancelable request
  src/views/Create.vue
Labels: 3. to review, bug, feature: 📑 form creation

#418 Fix variable-typo
  lib/Controller/ApiController.php
Labels: 3. to review, bug, feature: 📊 responses & statistics

#419 Include Logger for debugging
  lib/Controller/PageController.php
  lib/Service/FormsService.php
Labels: 3. to review, enhancement, technical debt

#391 Replace userId with userSession->UID
  lib/Controller/ApiController.php
  lib/Service/FormsService.php
Labels: 3. to review, enhancement, technical debt

#421 Fix Screenshot directory
  README.md
  screenshots/Create.PNG
  screenshots/List.PNG
  screenshots/Results.PNG
  screenshots/Vote.PNG
  screenshots/forms1.png
  screenshots/forms2.png
  screenshots/placeholder
Labels: 3. to review, bug
