Repository nextcloud/forms, pull requests merged in 2020-06, with the labels that each got.

#429 Use icon-add in primary-text color
  css/icons.scss
  src/views/Create.vue
Labels: 3. to review, bug

#424 Fix linebreak in description
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, bug, design, feature: 📑 form creation

#428 Keep focus when copy Share-Link
  src/components/AppNavigationForm.vue
  src/views/Results.vue
  src/views/Sidebar.vue
Labels: 3. to review, bug, feature: 📑 form creation

#386 Fix result order
  lib/Controller/ApiController.php
  lib/Service/FormsService.php
  src/components/Results/Answer.vue
  src/components/Results/Submission.vue
  src/views/Results.vue
Labels: 3. to review, bug, feature: 📊 responses & statistics, priority

#388 Delete empty options from Db
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionMultiple.vue
Labels: 3. to review, bug, feature: 📑 form creation

#413 Avoid Submit on Enter
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/views/Submit.vue
Labels: 3. to review, bug, feature: 📝 submitting responses

#389 Question-specific placeholders
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/models/AnswerTypes.js
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, design, enhancement, feature: 📑 form creation

#394 Fix some small MultipleInput issues
  src/components/Questions/QuestionMultiple.vue
Labels: 3. to review, bug, feature: 📑 form creation

#420 Fix public template header
  lib/Controller/PageController.php
Labels: 3. to review, bug, feature: 📝 submitting responses

#450 Add '(responses)' to export file name
  src/views/Results.vue
Labels: 3. to review, design, enhancement, feature: 📊 responses & statistics

#415 Enh/invalid warning
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/models/AnswerTypes.js
Labels: 3. to review, enhancement, feature: 📑 form creation

#454 Cleanup old files
  .l10nignore
  Forms_Support.md
  ISSUE_TEMPLATE.md
Labels: 3. to review

#452 Invert submitOnce on UI
  lib/Controller/ApiController.php
  src/views/Sidebar.vue
Labels: 3. to review, bug

#427 Allow navigation through edit via Tab-Key
  src/components/Questions/Question.vue
  src/components/Questions/QuestionMultiple.vue
Labels: 3. to review, bug, feature: 📑 form creation

#464 Change 'Mandatory' to simpler 'Required'
  src/components/Questions/Question.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, design, enhancement, feature: 📑 form creation, feature: 📝 submitting responses

#469 Fix submitting form with expiration-date.
  lib/Controller/ApiController.php
Labels: 3. to review, bug

#406 Put AppNavigationItems into proper Container
  src/Forms.vue
Labels: 4. to release, enhancement, feature: 📑 form creation

#478 Include version on feature-request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3. to review, enhancement
