Repository nextcloud/forms, pull requests merged in 2020-04, with the labels that each got.

#265 Enh/mandatory-questions
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
Labels: 3. to review, enhancement

#260 Fix/only own forms
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Db/FormMapper.php
  src/Forms.vue
  src/services/FormsService.js
  src/views/List.vue
Labels: 2. developing

#270 Order Questions
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Db/Question.php
  lib/Db/QuestionMapper.php
  lib/Migration/Version010200Date2020323141300.php
  src/views/Create.vue
Labels: 3. to review, enhancement

#278 Convert AccessList
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Form.php
  lib/Db/SubmissionMapper.php
  lib/Migration/Version010200Date2020323141300.php
  src/views/Sidebar.vue
  templates/submit.tmpl.php
Labels: 3. to review, enhancement

#287 Unique Form-Hash
  lib/Migration/Version010200Date2020323141300.php
Labels: 3. to review, bug

#288 Migrate Timestamps
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Form.php
  lib/Db/Submission.php
  lib/Migration/Version010200Date2020323141300.php
  src/views/Sidebar.vue
Labels: 3. to review

#289 Fix/api cleanup
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/FormMapper.php
Labels: 3. to review

#297 Further design improvements after review
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/Question.vue
  src/components/TopBar.vue
  src/components/shareDiv.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
Labels: 3. to review, design, enhancement

#306 Further design improvements after review
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/Question.vue
  src/components/TopBar.vue
  src/components/shareDiv.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
Labels: 3. to review, design, enhancement

#307 Delete dash
  src/components/Questions/Question.vue
Labels: design

#309 Further design fixes
  src/components/AppNavigationForm.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, design, enhancement

#310 Cleanup old src code
  src/components/_base-UserDiv.vue
  src/components/dateFormItem.vue
  src/components/quizFormItem.vue
  src/components/shareDiv.vue
  src/components/textFormItem.vue
  src/main.js
  src/plugins/ModalDialog.vue
  src/plugins/plugin.js
  src/router.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/img/app.svg
  src/views/img/expired-unvoted-vote.svg
  src/views/img/expired-voted-vote.svg
  src/views/img/open-unvoted-vote.svg
  src/views/img/open-voted-vote.svg
Labels: 3. to review, enhancement

#312 Fix question icons broken in dark theme
  img/answer-long.svg
  img/answer-short.svg
Labels: 3. to review, bug, design

#311 Bump copyrights & add php cs & fixed linting
  .gitattributes
  .github/workflows/lint.yml
  .gitignore
  .php_cs.dist
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Controller/SystemController.php
  lib/Db/Answer.php
  lib/Db/AnswerMapper.php
  lib/Db/Form.php
  lib/Db/FormMapper.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Question.php
  lib/Db/QuestionMapper.php
  lib/Db/Submission.php
  lib/Db/SubmissionMapper.php
  lib/Migration/Version0010Date20190000000007.php
  lib/Migration/Version010102Date20200323120846.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Service/FormsService.php
  license.php
  package-lock.json
  package.json
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/_base-UserDiv.vue
  src/components/resultItem.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
  templates/expired.php
  templates/main.php
  templates/notfound.php
  tests/bootstrap.php
  webpack.common.js
Labels: 3. to review, enhancement

#313 Comply to new Actions primary/title standard
  package-lock.json
  package.json
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, design, enhancement

#320 l10n: Fixed typo
  templates/notfound.php
Labels: 3. to review, bug
