Repository nextcloud/forms, pull requests merged in 2020-03, with the labels that each got.

#225 Small fixes
  appinfo/info.xml
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  src/components/_base-Controls.vue
Labels: 3. to review

#235 Cleanup the pagecontroller and vote template a bit
  lib/Controller/PageController.php
  templates/vote.tmpl.php
Labels: 3. to review

#247 Remove the notifications
  appinfo/info.xml
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Notification.php
  lib/Db/NotificationMapper.php
  lib/Migration/Version010102Date20200323120846.php
Labels: 3. to review, enhancement

#251 Description correction
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/views/List.vue
Labels: 3. to review, bug

#254 Fix audit
  package-lock.json
  package.json
Labels: 3. to review, dependencies, security

#252 Fix questions display
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Db/AnswerMapper.php
  lib/Db/QuestionMapper.php
  src/components/quizFormItem.vue
  src/views/Create.vue
Labels: 2. developing, bug

#257 Fix displaying of result info again
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/Db/VoteMapper.php
  src/views/Results.vue
Labels: 3. to review
