Repository nextcloud/forms, pull requests merged in 2020-02, with the labels that each got.

#130 Unnecessary $questions assignment removed
  lib/Controller/PageController.php
Labels: 4. to release, enhancement

#194 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 3. to review

#199 Make 'unique' an integer
  lib/Db/Event.php
Labels: 3. to review, bug

#207 Add github actions
  .github/workflows/dependabot-approve.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  composer.json
Labels: 3. to review

#208 Move to @nextcloud packages
  .eslintrc.js
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  .travis.yml
  Makefile
  babel.config.js
  package-lock.json
  package.json
  src/App.vue
  src/components/_base-CloudDiv.vue
  src/components/_base-Controls.vue
  src/components/_base-UserDiv.vue
  src/components/dateFormItem.vue
  src/components/formListItem.vue
  src/components/quizFormItem.vue
  src/components/resultItem.vue
  src/components/shareDiv.vue
  src/components/sideBarClose.vue
  src/components/textFormItem.vue
  src/main.js
  src/plugins/ModalDialog.vue
  src/plugins/plugin.js
  src/router.js
  src/views/Create.vue
  src/views/List.vue
  src/views/Results.vue
Labels: 3. to review, dependencies, enhancement, high

#209 Add CODECOV_TOKEN env
  .github/workflows/phpunit.yml
Labels: 3. to review

#215 Move navigation entry to info.xml
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
Labels: 3. to review
