Repository nextcloud/forms, pull requests merged in 2020-11, with the labels that each got.

#669 Fix DateTimePicker Formatter
  src/views/Sidebar.vue
Labels: 3. to review, dependencies

#673 Translators info on multiple choice
  src/models/AnswerTypes.js
Labels: 3. to review, papercut

#671 Fix time-formatting
  src/views/Sidebar.vue
  webpack.js
Labels: 3. to review, bug

#661 Bump eslint to 7 and associated dependencies
  package-lock.json
  package.json
  src/components/Questions/AnswerInput.vue
  src/views/Create.vue
Labels: 3. to review, enhancement

#672 Add Date & Datetime Component
  css/icons.scss
  img/answer-date.svg
  img/answer-datetime.svg
  lib/Db/Question.php
  src/components/Questions/QuestionDate.vue
  src/models/AnswerTypes.js
Labels: 3. to review, enhancement, feature: ❓ question types

#695 Fix Popover-Reference
  css/forms.scss
Labels: 3. to review, bug
