Repository nextcloud/forms, pull requests merged in 2021-04, with the labels that each got.

#881 Fix boolean columns nullable
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version020300Date20210403214012.php
Labels: 3. to review, bug

#882 Refactor Mandatory
  CHANGELOG.md
  appinfo/routes.php
  docs/API.md
  docs/DataStructure.md
  lib/Controller/ApiController.php
  lib/Db/Question.php
  lib/Migration/Version020300Date20210406114130.php
  lib/Migration/Version020300Date20210406133704.php
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review

#893 Some more tests
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review

#856 Delete a deleted Users Forms
  lib/AppInfo/Application.php
  lib/BackgroundJob/UserDeletedJob.php
  lib/Controller/ApiController.php
  lib/Db/FormMapper.php
  lib/Listener/UserDeletedListener.php
  tests/Unit/BackgroundJob/UserDeletedJobTest.php
  tests/Unit/Listener/UserDeletedListenerTest.php
Labels: 3. to review, enhancement

#895 Add server-side validation of submissions
  lib/Controller/ApiController.php
  lib/Service/SubmissionService.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review, bug, enhancement, feature: 📝 submitting responses
