Repository nextcloud/forms, pull requests merged in 2021-03, with the labels that each got.

#815 Clarify translations
  lib/Activity/Provider.php
  lib/Controller/ApiController.php
  lib/Service/SubmissionService.php
  src/components/AppNavigationForm.vue
  src/components/Questions/Question.vue
  src/components/Results/Summary.vue
  src/views/Create.vue
  src/views/Sidebar.vue
Labels: 3. to review, design

#820 Use new RichObject
  lib/Activity/Provider.php
Labels: 3. to review, enhancement

#804 Fix anonymous text
  lib/Controller/PageController.php
  src/FormsSubmit.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, bug

#816 Disable iPhone Auto-Zoom
  lib/Controller/PageController.php
Labels: 3. to review, bug

#829 Fix compliance
  Makefile
  lib/Migration/Version010200Date20200323141300.php
Labels: 3. to review

#837 Fix router naming conflict
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: 3. to review, bug

#835 Fix Summary Aggregation
  src/components/Results/Summary.vue
Labels: 3. to review, bug

#844 Fix half access objects
  appinfo/info.xml
  lib/Controller/ApiController.php
  lib/Migration/Version020202Date20210311150843.php
Labels: 3. to review, bug

#846 Fix Routing
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: 3. to review, bug

#854 Fix Dependabot Auto-Approve
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review

#860 Fix export multiple answers
  lib/Service/SubmissionService.php
Labels: 3. to review, bug

#845 Fix activity l10n & make codecov happy
  .gitignore
  composer.json
  lib/Activity/Provider.php
  tests/Unit/Activity/ActivityManagerTest.php
  tests/Unit/Activity/FilterTest.php
  tests/Unit/Activity/ProviderTest.php
  tests/Unit/Activity/Settings/FormsActivitySettingsTest.php
  tests/Unit/Activity/Settings/NewShareTest.php
  tests/Unit/Activity/Settings/NewSubmissionTest.php
Labels: 2. developing, enhancement

#864 Include Composer lock
  .gitignore
  composer.lock
Labels: 3. to review

#871 Fix export again :(
  lib/Service/SubmissionService.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review, bug

#872 Bump dependencies and webpack 5
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#821 Fix codecov token
  .github/workflows/phpunit.yml
  .gitignore
  codecov.yml
  composer.json
  phpunit.integration.xml
  phpunit.xml
  tests/phpunit.integration.xml
  tests/phpunit.unit.xml
Labels: 4. to release, bug
