Repository nextcloud/forms, pull requests merged in 2022-12, with the labels that each got.

#1381 More usable and accessible navigation between View/Edit/Results
  src/Forms.vue
  src/components/TopBar.vue
  src/mixins/ViewsMixin.js
  src/router.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
Labels: enhancement, help wanted, design, 4. to release, feature: 📑 form creation

#1383 Init all answers from props
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
Labels: enhancement, javascript, 3. to review, feature: 📝 submitting responses

#1139 make forms OCS API CORS compatible
  appinfo/routes.php
  lib/Controller/ApiController.php
Labels: enhancement, 3. to review

#1393 Fix question header title for extra long text
  src/components/Questions/Question.vue
Labels: bug, design, 3. to review

#1427 Move to main branch
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#1428 Update workflows
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  composer.json
  vendor-bin/cs-fixer/composer.json
Labels: 4. to release, technical debt

#1433 Fix export
  lib/Controller/ApiController.php
  src/views/Results.vue
Labels: bug, 3. to review
