Repository nextcloud/forms, pull requests merged in 2022-08, with the labels that each got.

#1269 Fix Add Question a11y
  src/views/Create.vue
Labels: bug, 3. to review

#1275 Move to Psr\Log\LoggerInterface
  lib/Activity/ActivityManager.php
  lib/Activity/Provider.php
  lib/BackgroundJob/UserDeletedJob.php
  lib/Controller/ApiController.php
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  lib/Controller/ShareApiController.php
  lib/Listener/UserDeletedListener.php
  lib/Service/ConfigService.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  tests/Unit/Activity/ActivityManagerTest.php
  tests/Unit/Activity/ProviderTest.php
  tests/Unit/BackgroundJob/UserDeletedJobTest.php
  tests/Unit/Controller/ConfigControllerTest.php
  tests/Unit/Controller/ShareApiControllerTest.php
  tests/Unit/Listener/UserDeletedListenerTest.php
  tests/Unit/Service/ConfigServiceTest.php
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review

#1270 Set border color to maxcontrast
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
Labels: 3. to review

#1282 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1286 Update npm and node engines versions
  package.json
Labels: dependencies

#1285 Update Marcos Email
  src/utils/CancelableRequest.js
Labels: 3. to review

#1168 Rework Navigation
  lib/Db/SubmissionMapper.php
  lib/Service/FormsService.php
  src/components/AppNavigationForm.vue
  tests/Unit/Service/FormsServiceTest.php
Labels: design, 3. to review

#1283 Use MutliSelect for dropdown questions
  src/components/Questions/QuestionDropdown.vue
Labels: 3. to review

#1298 Use NC/vue beta 3
  package-lock.json
  package.json
  src/Forms.vue
  src/FormsSettings.vue
  src/FormsSubmit.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Results/Submission.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
Labels: dependencies, 3. to review

#1304 Move Question Icons to Material Design
  css/icons.scss
  img/answer-checkbox.svg
  img/answer-date.svg
  img/answer-datetime.svg
  img/answer-dropdown.svg
  img/answer-long.svg
  img/answer-multiple.svg
  img/answer-short.svg
  img/answer-time.svg
  src/models/AnswerTypes.js
  src/views/Create.vue
Labels: enhancement, design, 3. to review

#1281 Move to button component & first material icons
  src/Forms.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Results.vue
Labels: design, 3. to review

#1303 Update Forms Icon and create Component
  img/forms-dark.svg
  img/forms.svg
  src/components/AppNavigationForm.vue
  src/components/Icons/FormsIcon.vue
Labels: enhancement, design, 3. to review

#1243 User migration
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/FormsMigrator.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, 4. to release

#1305 More Icons!
  src/components/AppNavigationForm.vue
  src/components/Icons/IconCopyAll.vue
  src/components/Questions/AnswerInput.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/views/Sidebar.vue
Labels: enhancement, design, 3. to review

#1306 Make CHANGELOG.md parseable by the appstore
  CHANGELOG.md
Labels: 3. to review
