Repository nextcloud/forms, pull requests merged in 2022-09, with the labels that each got.

#1321 Empty Content to Vue
  lib/Constants.php
  lib/Controller/PageController.php
  src/FormsEmptyContent.vue
  src/emptyContent.js
  templates/emptyContent.php
  templates/nosubmit.php
  webpack.js
Labels: 3. to review, technical debt

#1320 Add UI to preview and fill out own forms
  src/components/AppNavigationForm.vue
  src/components/TopBar.vue
  src/mixins/ViewsMixin.js
  src/router.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  webpack.js
Labels: enhancement, design, 4. to release

#1335 Fixing several small things
  css/forms.css
  css/public.css
  lib/Controller/PageController.php
  src/FormsEmptyContent.vue
  src/components/Questions/Question.vue
  src/components/TopBar.vue
  src/emptyContent.js
  src/views/Submit.vue
  templates/emptyContent.php
Labels: 3. to review

#1334 Fix migration 20220414 not working on SQLite
  lib/Migration/Version030000Date20220414203511.php
Labels: bug, high, 3. to review

#1342 Make dropdown searchable
  src/components/Questions/QuestionDropdown.vue
Labels: enhancement, 3. to review

#1271 Feature: Allow shuffling of answer options | Sort options
  lib/Controller/ApiController.php
  lib/Db/Question.php
  lib/Migration/Version030000Date20220831195000.php
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/mixins/QuestionMixin.js
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 4. to release

#1338 Adjust styling for NC25 & Update `@nextcloud/vue`
  package-lock.json
  package.json
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: 4. to release

#1344 Adjust design based on Design Review
  src/components/AppNavigationForm.vue
  src/components/Results/Submission.vue
  src/components/Results/Summary.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: design, 3. to review

#1348 minversion 25
  .github/workflows/phpunit.yml
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version030000Date20220831195000.php
Labels: 3. to review

#1351 Fix alignment of "Add question" button
  src/views/Create.vue
Labels: 3. to review

#1360 Remove css variables
  css/forms.css
Labels: bug, 3. to review

#1356 Use `--gradient-primary-background` for summary
  src/components/Results/Summary.vue
Labels: design, 3. to review, regression

#1322 Use NcCheckboxRadioSwitch for QuestionMultiple
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionMultiple.vue
Labels: 3. to review

#1352 Remove unneeded css
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
Labels: 3. to review

#1359 Fix Actions Container
  src/components/Questions/Question.vue
Labels: bug, 3. to review

#1362 Fix question movement
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
Labels: design, 3. to review

#1363 Fix datepicker height
  src/components/Questions/QuestionDate.vue
Labels: bug, design, 3. to review

#1364 Adjust look of long text questions
  src/components/Questions/QuestionLong.vue
Labels: bug, design, 3. to review
