Repository nextcloud/forms, pull requests merged in 2022-10, with the labels that each got.

#1368 Remove isDropdown condition
  src/components/Questions/QuestionMultiple.vue
Labels: bug, 3. to review, regression

#1370 Fix aria warning
  src/components/AppNavigationForm.vue
Labels: 3. to review

#1371 Fix lint warning
  src/components/AppNavigationForm.vue
Labels: 3. to review, technical debt

#1375 v3.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: pending fix, 4. to release

#1388 Fix CI runs for postgres
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#1389 Use user's timezone for timestamps in CSV export
  lib/Service/SubmissionService.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: bug, php, 3. to review, feature: 📊 responses & statistics

#1391 Fix `setExtraSettings` to accept same type as `getExtraSettings`
  lib/Controller/ApiController.php
  lib/Db/Question.php
  tests/Unit/Service/FormsServiceTest.php
Labels: bug, php, 3. to review
