Repository nextcloud/forms, pull requests merged in 2022-03, with the labels that each got.

#1134 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1141 Replace deprecated String.prototype.substr()
  src/utils/GenRandomId.js
Labels: 4. to release

#1151 Fix tests
  tests/Unit/Activity/ActivityManagerTest.php
  tests/Unit/Activity/FilterTest.php
  tests/Unit/Activity/ProviderTest.php
  tests/Unit/Activity/Settings/FormsActivitySettingsTest.php
  tests/Unit/Activity/Settings/NewShareTest.php
  tests/Unit/Activity/Settings/NewSubmissionTest.php
  tests/Unit/BackgroundJob/UserDeletedJobTest.php
  tests/Unit/Listener/UserDeletedListenerTest.php
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 4. to release, technical debt
