Repository nextcloud/forms, pull requests merged in 2022-07, with the labels that each got.

#1199 Restrict Form Creation & Sharing Settings
  appinfo/info.xml
  appinfo/routes.php
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  lib/Controller/ShareApiController.php
  lib/Service/ConfigService.php
  lib/Service/FormsService.php
  lib/Settings/Settings.php
  lib/Settings/SettingsSection.php
  src/Forms.vue
  src/FormsSettings.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/settings.js
  templates/settings.php
  tests/Unit/Controller/ConfigControllerTest.php
  tests/Unit/Controller/ShareApiControllerTest.php
  tests/Unit/Service/ConfigServiceTest.php
  tests/Unit/Service/FormsServiceTest.php
  webpack.js
Labels: enhancement, 4. to release

#1242 Fix sharing icons
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/TopBar.vue
Labels: bug, design, 3. to review

#1274 Use `@nextcloud/logger` for frontend logging
  .eslintrc.js
  package-lock.json
  package.json
  src/Forms.vue
  src/FormsSettings.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/mixins/QuestionMixin.js
  src/mixins/ViewsMixin.js
  src/utils/Logger.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: enhancement, javascript, 3. to review
