Repository nextcloud/forms, pull requests merged in 2022-04, with the labels that each got.

#1150 Minversion 22
  appinfo/info.xml
  lib/Activity/Provider.php
  tests/Unit/Activity/ProviderTest.php
Labels: integration, 3. to review

#1158 Include Capabilities Response
  lib/AppInfo/Application.php
  lib/Capabilities.php
Labels: enhancement, integration, 3. to review

#1159 Bump php-dependencies
  .github/workflows/lint.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  license.php
  tests/phpunit.integration.xml
  tests/phpunit.unit.xml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: dependencies, 3. to review

#1161 Update master php testing versions
  composer.json
  tests/phpunit.integration.xml
  tests/phpunit.xml
Labels: 4. to release

#1162 Rollback Capabilities
  lib/Capabilities.php
Labels: 3. to review

#1163 2.5.0
  .github/workflows/appstore-build-publish.yml
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1156 Remove old forms tables
  lib/Migration/Version030000Date20220402151229.php
Labels: 4. to release, technical debt

#1001 Make date/time answers consistent
  css/icons.scss
  docs/DataStructure.md
  img/answer-time.svg
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Db/Question.php
  lib/Service/SubmissionService.php
  src/components/Questions/QuestionDate.vue
  src/models/AnswerTypes.js
  src/views/Create.vue
  src/views/Results.vue
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, 3. to review, feature: 📊 responses & statistics, feature: ❓ question types

#1172 Add Question Description
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Question.php
  lib/Migration/Version030000Date20220414203511.php
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review

#1185 Fix Readme
  README.md
  composer.json
Labels: 3. to review

#1175 Upload coverage only once
  .github/workflows/phpunit.yml
Labels: 3. to review
