Repository nextcloud/forms, pull requests merged in 2023-12, with the labels that each got.

#1819 Use dependabot for stable3
  .github/dependabot.yml
Labels: 3. to review, technical debt

#1826 Remove deprecated setModal
  src/views/Results.vue
Labels: bug, 3. to review

#1827 enh(dev): Migrate from webpack to vite for building the frontend
  .eslintrc.js
  .eslintrc.json
  .gitignore
  babel.config.js
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/main.js
  src/settings.js
  src/submit.js
  stylelint.config.cjs
  vite.config.js
  webpack.js
Labels: 3. to review

#1805 enh: Allow to set `results_delete` permission on the frontend
  lib/Controller/ApiController.php
  lib/Controller/ShareApiController.php
  lib/Service/FormsService.php
  src/components/SidebarTabs/SharingShareDiv.vue
  src/views/Results.vue
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/Controller/ShareApiControllerTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review, feature: 📊 responses & statistics

#1828 enh: Add Forms to header title on public link view
  lib/Controller/PageController.php
Labels: enhancement, php, backport-request, design, 3. to review

#1416 transfer ownership of a form
  appinfo/routes.php
  docs/API.md
  lib/Controller/ApiController.php
  src/Forms.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/TransferOwnership.vue
  src/mixins/UserSearchMixin.js
Labels: enhancement, 3. to review

#1832 Fix typo in PR feedback action
  .github/pr-feedback.yml
Labels: bug, backport-request, 3. to review, technical debt

#1839 chore: Update `@nextcloud/vite-config` to fix dev builds
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#1423 Question duplication
  appinfo/routes.php
  docs/API.md
  lib/Controller/ApiController.php
  src/components/Questions/Question.vue
  src/mixins/QuestionMixin.js
  src/views/Create.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: enhancement, 3. to review

#1848 chore: Update `vite` to v5
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#1849 fix(Question): Do not place popover within question but on body
  src/components/Questions/Question.vue
Labels: bug, 3. to review

#1851 fix(Question): close question menu after copy question
  src/components/Questions/Question.vue
Labels: bug, javascript, 3. to review, regression, feature: 📑 form creation

#1853 fix: Use separate chunk for `vue` and `vue-router` to prevent multiple imports
  vite.config.js
Labels: bug, 3. to review

#1852 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies, 3. to review, automated

#1663 enh: Replace confirm dialog for deletion with NcDialog
  src/components/AppNavigationForm.vue
Labels: enhancement, design, 3. to review

#1863 chore: replace isMobile mixin with useIsMobile composable
  src/Forms.vue
  src/components/TopBar.vue
Labels: javascript, 3. to review, technical debt
