Repository nextcloud/forms, pull requests merged in 2023-10, with the labels that each got.

#1736 Replace outdated screenshots in Readme.md
  screenshots/forms1.png
  screenshots/forms2.png
  screenshots/forms3.png
Labels: 3. to review

#1740 Update composer.lock after dropping php 7.4
  composer.lock
  vendor-bin/cs-fixer/composer.lock
Labels: dependencies, php, 3. to review

#1739 Update README.md
  README.md
Labels: 3. to review

#1731 fix: Warning about missing label for other answer
  src/components/Questions/QuestionMultiple.vue
Labels: enhancement, 3. to review

#1730 fix: Incorrect type for empty extraSettings in frontend
  src/mixins/QuestionMixin.js
Labels: javascript, 3. to review, regression

#1467 Feature: Allow to share forms with Circles
  .github/workflows/phpunit.yml
  lib/Activity/ActivityConstants.php
  lib/Activity/ActivityManager.php
  lib/Activity/Provider.php
  lib/Constants.php
  lib/Controller/ShareApiController.php
  lib/Service/CirclesService.php
  lib/Service/FormsService.php
  psalm.xml
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/mixins/ShareTypes.js
  tests/Unit/Activity/ActivityManagerTest.php
  tests/Unit/Activity/ProviderTest.php
  tests/Unit/Controller/ShareApiControllerTest.php
  tests/Unit/Service/CirclesServiceTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review, feature: 👥 sharing settings

#1745 fix(docs): Add changes of API 2.1 to the API docs
  docs/API.md
Labels: enhancement, pending documentation, 3. to review

#1310 Implement warning when leaving an unsubmitted form
  src/views/Submit.vue
Labels: enhancement, javascript, 3. to review, feature: 📝 submitting responses

#1746 feat(ActivityManager): Send notification about new submissions to circle memebers
  lib/Activity/ActivityManager.php
  tests/Unit/Activity/ActivityManagerTest.php
Labels: enhancement, php, 3. to review

#1659 feat: Implement custom submission message
  docs/API.md
  docs/DataStructure.md
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Db/Form.php
  lib/Migration/Version030400Date20230628011500.php
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/scssmixins/markdownOutput.scss
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review, feature: 📝 submitting responses

#1532 Allow reordering questions using the keyboard
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/views/Create.vue
Labels: enhancement, design, 3. to review

#1759 Fix inverted sorting in frontend for shared forms
  src/Forms.vue
Labels: bug, javascript, design, 3. to review

#1762 chore(deps): Remove `core-js` from dependencies as we no longer use it.
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#1764 fix: Make sure "other" answers are correctly handled
  lib/Controller/ApiController.php
  lib/Service/SubmissionService.php
  src/components/Questions/QuestionMultiple.vue
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: bug, 3. to review

#1770 fix(lint): add missing trailing commas
  src/utils/CancelableRequest.js
  src/views/Results.vue
Labels: javascript, 3. to review
