Repository nextcloud/forms, pull requests merged in 2023-01, with the labels that each got.

#1438 Move from `christophwurst/nextcloud` to `nextcloud/ocp`
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.lock
Labels: dependencies, 3. to review

#1441 Show info message only if available
  src/views/Submit.vue
Labels: design, 3. to review

#1440 Import form question extra settings
  lib/FormsMigrator.php
  tests/Unit/FormsMigratorTest.php
Labels: bug, 3. to review

#1450 Fix Typo
  tests/Unit/Activity/Settings/FormsActivitySettingsTest.php
Labels: 3. to review

#1447 Scope SCSS in Create.vue and adjust Results.vue
  src/views/Create.vue
  src/views/Results.vue
Labels: design, 3. to review

#1432 Show relative expiration date inside form
  docs/API.md
  docs/DataStructure.md
  lib/Controller/ApiController.php
  lib/Db/Form.php
  lib/FormsMigrator.php
  lib/Migration/Version030100Date20221231100426.php
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/views/Create.vue
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review, feature: 📝 submitting responses

#1456 Fix public insert
  lib/Controller/ApiController.php
Labels: bug, 3. to review

#1449 Enable PHPUnit integration tests and fix them
  .github/workflows/phpunit.yml
  lib/Controller/ApiController.php
  lib/Db/Answer.php
  lib/Db/Form.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Question.php
  lib/Db/Share.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version030000Date20211206213004.php
  lib/Migration/Version030100Date20230115214242.php
  tests/Integration/Api/ApiV2Test.php
  tests/phpunit.integration.xml
Labels: php, 3. to review

#1460 Update phpunit.yml to work with current Server master
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#1463 Fix cors on ShareApi
  lib/Controller/ShareApiController.php
Labels: bug, 3. to review

#1465 Fix insert
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Middleware/PublicCorsMiddleware.php
Labels: bug, high, 3. to review

#1470 feat: Add slot for additional actions to the question component
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
Labels: enhancement, javascript, 3. to review

#1461 Allow sharees to see results | Implement `PERMISSION_RESULTS`
  appinfo/routes.php
  docs/API.md
  docs/DataStructure.md
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Controller/ShareApiController.php
  lib/Db/Share.php
  lib/Migration/Version030100Date20230123182700.php
  lib/Service/FormsService.php
  src/components/Results/Submission.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/TopBar.vue
  src/mixins/PermissionTypes.js
  src/views/Results.vue
  src/views/Sidebar.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/Controller/ShareApiControllerTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 4. to release, feature: 📊 responses & statistics

#1473 Add missing computed property to edit view
  src/views/Create.vue
Labels: bug, 3. to review
