Repository nextcloud/forms, pull requests merged in 2023-11, with the labels that each got.

#1769 Move parameter typing for extraSettings
  lib/Controller/ApiController.php
  lib/Db/Question.php
  tests/Unit/Service/FormsServiceTest.php
Labels: php, 3. to review

#1382 Remember input in LocalStorage
  src/views/Submit.vue
Labels: enhancement, 3. to review, feature: 📝 submitting responses

#1750 fix: Make form editable with keyboard
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/views/Create.vue
Labels: enhancement, javascript, 3. to review, feature: 📑 form creation

#1784 fix: Fix import of debounce
  src/mixins/QuestionMixin.js
Labels: bug, regression

#1491 Add subtypes for short input, like email, phone or custom regex
  docs/DataStructure.md
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  src/models/ValidationTypes.js
  src/utils/RegularExpression.js
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, php, javascript, 3. to review

#1786 fix(Submit): Make `answers` reactive and fix invalid mutation of computed property
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionMultiple.vue
  src/views/Submit.vue
Labels: bug, 3. to review

#1791 Fix missing column in DataStructure.md
  docs/DataStructure.md
Labels: bug, 3. to review

#1793 [stable3] fix(tests): Adjust tests to run on stable27 max.
  .github/workflows/phpunit.yml
Labels: 3. to review

#1796 Min server 28
  appinfo/info.xml
Labels: 3. to review, technical debt

#1797 chore: Bump version to 4.0.0-alpha for main branch
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1795 chore(phpunit): Switch to phpunit workflow from organization
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  tests/Integration/Api/ApiV2Test.php
Labels: 3. to review

#1696 Make components compatible to nextcloud-vue 8
  src/Forms.vue
  src/FormsEmptyContent.vue
  src/FormsSettings.vue
  src/components/AppNavigationForm.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
Labels: javascript, design, 3. to review, technical debt

#1798 fix: Adjust composer scripts to work when only installing production dependencies
  composer.json
Labels: 3. to review

#1800 fix(QuestionMultiple): Fix setting the `allowOtherAnswer` option
  src/components/Questions/QuestionMultiple.vue
Labels: bug, backport-request, 3. to review

#1804 chore: Update `nextcloud/ocp` for main to `stable28`
  composer.json
  composer.lock
  lib/Capabilities.php
Labels: dependencies, 3. to review

#1806 fix: add canMoveUp/Down props to QuestionMixin
  src/mixins/QuestionMixin.js
Labels: javascript, backport-request, 3. to review, regression, feature: 📑 form creation

#1803 enh: Show confirmation dialog before submitting an empty form
  .eslintrc.js
  package-lock.json
  package.json
  src/views/Submit.vue
  webpack.js
Labels: enhancement, 3. to review, feature: 📝 submitting responses

#1802 enh(sharing): Move away from deprecated icon classes and allow to search user by email
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/mixins/ShareTypes.js
Labels: enhancement, javascript, 3. to review, feature: 👥 sharing settings
