Repository nextcloud/forms, pull requests merged in 2023-06, with the labels that each got.

#1638 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/node.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#1644 Switch OCI image in PHPUnit workflow
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#1649 chore: update node engines to next LTS
  package.json
Labels: dependencies, 3. to review, automated

#1553 Add technical identifiers for questions
  docs/API.md
  docs/DataStructure.md
  lib/Db/Question.php
  lib/Migration/Version030200Date20230307141800.php
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/mixins/QuestionMixin.js
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, 3. to review

#1661 Update package-lock.json
  package-lock.json
Labels: dependencies, 3. to review

#1660 fix: Sanitize file name when writing a CSV file
  lib/Service/SubmissionService.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: bug, 3. to review, feature: 📊 responses & statistics

#1658 Reduce white space between questions
  src/components/Questions/Question.vue
Labels: enhancement, design, 3. to review, feature: 📑 form creation, feature: 📝 submitting responses
