Repository nextcloud/forms, pull requests merged in 2023-05, with the labels that each got.

#1574 fix: Replace `NcRichContenteditable` with `textarea`
  css/forms.css
  src/components/Questions/Question.vue
  src/scssmixins/markdownOutput.scss
  src/views/Create.vue
  src/views/Submit.vue
Labels: bug, 3. to review, feature: 📑 form creation

#1625 Prepare for NC27
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#1635 Drop 'Nextcloud' from connected responses string
  src/views/Create.vue
  src/views/Submit.vue
Labels: enhancement, 3. to review
