Repository nextcloud/forms, pull requests merged in 2023-02, with the labels that each got.

#1476 Add shareHash parameter
  docs/API.md
Labels: 3. to review

#1480 Add test for method `newForm` of `ApiController`
  tests/Unit/Controller/ApiControllerTest.php
Labels: enhancement, 3. to review

#1490 Fix some small `SubmissionService` issues
  lib/Service/SubmissionService.php
Labels: bug, php, 3. to review

#1492 Fix public view
  lib/Service/FormsService.php
  tests/Unit/Service/FormsServiceTest.php
Labels: bug, 3. to review

#1489 Add Nextcloud 26 support
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: enhancement, 3. to review

#1499 Fix codecov action, auto-update actions
  .github/dependabot.yml
  .github/workflows/phpunit.yml
Labels: dependencies, 3. to review

#1519 Fix `stable2` phpunit workflows - run on stable24 instead of master
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
Labels: bug, 3. to review

#1498 Fix Create edit mode
  src/views/Create.vue
Labels: bug, 3. to review

#1525 [stable2] Update vue and webpack dependencies
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#1479 Add lastUpdated property to Form
  lib/Controller/ApiController.php
  lib/Controller/ShareApiController.php
  lib/Db/Form.php
  lib/Db/FormMapper.php
  lib/FormsMigrator.php
  lib/Migration/Version030100Date20230202175747.php
  lib/Service/FormsService.php
  src/Forms.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/mixins/QuestionMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, php, javascript, design, 3. to review

#1529 Add information about API to appinfo
  appinfo/info.xml
Labels: enhancement, 3. to review

#1530 Make skip to content buttons work
  lib/Controller/PageController.php
Labels: bug, 3. to review
