Repository nextcloud/forms, pull requests merged in 2023-03, with the labels that each got.

#1539 Move API to v2.1
  appinfo/routes.php
  docs/API.md
  lib/Capabilities.php
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/mixins/QuestionMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
Labels: bug, php, javascript, 3. to review

#1548 [stable2] Drop stable22 & stable23 tests
  .github/workflows/phpunit.yml
Labels: 3. to review

#1542 Fix paragraph rendering
  src/components/Questions/Question.vue
  src/scssmixins/markdownOutput.scss
  src/views/Create.vue
  src/views/Submit.vue
Labels: bug, 3. to review

#1531 Make timestamp in csv export ISO 8601 compliant
  lib/Service/SubmissionService.php
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, php, 3. to review

#1471 Replace deprecated NcMultiselect with recommended NcSelect
  src/FormsSettings.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
Labels: javascript, 3. to review

#1555 Add note about Markdown formatting within description placeholder
  src/components/Questions/Question.vue
  src/views/Create.vue
Labels: enhancement, 3. to review, usability test

#1568 fix(markdown): Add margin for all new paragraphs
  src/scssmixins/markdownOutput.scss
Labels: bug, design, 3. to review

#1554 Place actions popover so it does not overflow the page
  src/components/Questions/Question.vue
Labels: bug, design, 3. to review
