Repository nextcloud/forms, pull requests merged in 2024-11, with the labels that each got.

#2397 (fix) default timezone for export
  lib/Service/SubmissionService.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: bug, backport-request, 3. to review

#2400 Add padding and max width so they don't stick to right screen border
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionFile.vue
  src/views/Submit.vue
Labels: enhancement, backport-request, design, 3. to review

#2401 fix: simplify mime-type checks to support jpg and other image formats
  lib/Controller/ApiController.php
  lib/Service/FormsService.php
  tests/Unit/Service/FormsServiceTest.php
Labels: bug, backport-request, 3. to review

#2408 feat: Refactor form sync to run as a background job with retry
  lib/BackgroundJob/SyncSubmissionsWithLinkedFileJob.php
  lib/Controller/ApiController.php
  tests/Unit/BackgroundJob/SyncSubmissionsWithLinkedFileJobTest.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: bug, php, backport-request, 3. to review
