Repository nextcloud/forms, pull requests merged in 2024-02, with the labels that each got.

#1920 Hide linked file actions from users who have access to results view
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Service/FormsService.php
  src/views/Results.vue
  tests/Unit/Controller/ApiControllerTest.php
Labels: bug, 3. to review

#1932 Update API version to v2.4
  appinfo/routes.php
  docs/API.md
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/SidebarTabs/TransferOwnership.vue
  src/mixins/QuestionMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
Labels: 3. to review, technical debt

#1944 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#1963 fix: Load styles also for settings section
  lib/Settings/Settings.php
Labels: bug, 3. to review

#1969 fix: Update moment format for date parsing
  src/components/Questions/QuestionDate.vue
  src/models/AnswerTypes.js
Labels: bug, 3. to review, feature: 📝 submitting responses

#1976 Update cypress.yml
  .github/workflows/cypress.yml
Labels: 3. to review, technical debt
