Repository nextcloud/forms, pull requests merged in 2024-03, with the labels that each got.

#1992 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#2000 Rename Circles to Teams in UI/logging
  lib/Activity/Provider.php
  lib/Controller/ShareApiController.php
  lib/Service/CirclesService.php
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  tests/Unit/Activity/ProviderTest.php
Labels: discussion, design, 3. to review

#2005 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#2010 chore: Adjust NPM version to 10 to match current Node LTS 20
  package-lock.json
  package.json
Labels: dependencies, 3. to review, technical debt

#2011 chore: update deps
  composer.lock
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  package-lock.json
  package.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies, 3. to review, technical debt

#2015 fix(TopBar): provide optional button text via new slot syntax
  src/components/TopBar.vue
Labels: bug, backport-request, 3. to review

#2013 Show expired shared forms to users with results permission
  lib/Service/FormsService.php
Labels: bug, php, backport-request, 3. to review, feature: 👥 sharing settings

#1925 feat: Add forms `state` to close and archive forms
  docs/API.md
  docs/DataStructure.md
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Db/Form.php
  lib/Migration/Version040200Date20240219201500.php
  lib/Service/FormsService.php
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/ArchivedFormsModal.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/TopBar.vue
  src/models/FormStates.ts
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
  tsconfig.json
Labels: enhancement, 3. to review, feature: 📑 form creation

#2021 fix: Do not show trailing button for technical name input
  src/components/Questions/Question.vue
Labels: bug, design, 3. to review

#1576 Reuse top bar component for responses view toggle
  package-lock.json
  package.json
  src/components/PillMenu.vue
  src/components/TopBar.vue
  src/views/Results.vue
Labels: bug, design, 3. to review

#2033 fix: remove positive lookbehind for finding unescaped slashes
  src/utils/RegularExpression.js
Labels: bug, javascript, backport-request, 3. to review
