Repository nextcloud/forms, pull requests merged in 2024-08, with the labels that each got.

#2232 fix: Add support for adding new entries with IME input
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/mixins/QuestionMixin.js
Labels: bug, 3. to review, feature: 📑 form creation

#2267 test: Add e2e test for IME input
  playwright/e2e/ime-input.spec.ts
  playwright/support/sections/AppNavigationSection.ts
  playwright/support/sections/FormSection.ts
  playwright/support/sections/QuestionSection.ts
  playwright/support/sections/QuestionType.ts
  src/components/Questions/AnswerInput.vue
Labels: 3. to review

#2268 fix: Fix form view without permissions
  src/Forms.vue
Labels: bug, 3. to review

#2277 feat: add warning about removing legacy links
  CHANGELOG.en.md
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: enhancement, design, 3. to review, feature: 👥 sharing settings

#2280 fix: add `target="_blank"` to links in description
  src/mixins/ViewsMixin.js
Labels: enhancement, javascript, 3. to review, feature: 📑 form creation

#2278 fix: Adjust app to be compatible with Nextcloud 30
  appinfo/info.xml
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/components/Results/ResultsSummary.vue
  src/components/Results/Submission.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: bug, 3. to review

#2283 test: Add e2e tests for form description
  playwright/e2e/form-description.spec.ts
  playwright/support/fixtures/topBar.ts
  playwright/support/sections/FormSection.ts
  playwright/support/sections/TopBarSection.ts
  src/components/TopBar.vue
Labels: 3. to review

#2270 chore: unify __construct functions
  lib/Activity/ActivityManager.php
  lib/Activity/Filter.php
  lib/Activity/Settings/FormsActivitySettings.php
  lib/BackgroundJob/CleanupUploadedFilesJob.php
  lib/BackgroundJob/UserDeletedJob.php
  lib/Capabilities.php
  lib/Controller/ApiController.php
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  lib/Db/AnswerMapper.php
  lib/Db/Option.php
  lib/Db/Question.php
  lib/Db/QuestionMapper.php
  lib/Db/Share.php
  lib/Db/Submission.php
  lib/Db/SubmissionMapper.php
  lib/Db/UploadedFile.php
  lib/FormsMigrator.php
  lib/Listener/UserDeletedListener.php
  lib/Service/ConfigService.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  lib/Settings/Settings.php
  lib/Settings/SettingsSection.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review

#2259 fix: Improve styles of layout for QuestionFile #2253
  src/components/Questions/QuestionFile.vue
Labels: bug, design, 3. to review

#2284 chore: Update workflows to fix release process
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
Labels: bug, 3. to review

#2291 fix(submit): `access` is unset for public forms so check for existance first
  src/views/Submit.vue
Labels: bug, 3. to review, regression

#2292 Fix: Show complete title in TransferOwnership dialog
  src/components/SidebarTabs/TransferOwnership.vue
Labels: bug, javascript, 3. to review

#2299 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
Labels: dependencies, 3. to review, automated

#2300 fix: make FilePicker work with latest dialogs
  .prettierignore
  src/views/Results.vue
Labels: 3. to review, regression

#2306 enh: make show to all users an admin setting
  lib/Constants.php
  lib/Service/ConfigService.php
  lib/Service/FormsService.php
  src/FormsSettings.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  tests/Unit/Controller/ConfigControllerTest.php
  tests/Unit/Service/ConfigServiceTest.php
Labels: enhancement, 3. to review, feature: 👥 sharing settings
