Repository nextcloud/forms, pull requests merged in 2024-10, with the labels that each got.

#2342 Fix Sass deprecation warning
  src/scssmixins/markdownOutput.scss
  src/views/Submit.vue
Labels: 3. to review, technical debt

#2333 feat: Allow to reorder options for "multiple" question type in backend
  appinfo/routes.php
  docs/API.md
  docs/API_v3.md
  lib/Controller/ApiController.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/QuestionMapper.php
  lib/Migration/Version040300Date20240420155356.php
  tests/Integration/Api/ApiV2Test.php
  tests/Integration/Api/ApiV3Test.php
  tests/Integration/IntegrationBase.php
  tests/Unit/Service/FormsServiceTest.php
Labels: enhancement, php, 3. to review, feature: 📑 form creation

#2343 fix(export): remove new lines from form title in the exported filename
  lib/Service/FormsService.php
  tests/Unit/Service/FormsServiceTest.php
Labels: bug, php, 3. to review

#2319 feat: Ask for restarting submission if form was changed
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/views/Submit.vue
Labels: enhancement, javascript, 2. developing, feature: 📝 submitting responses

#2354 fix(stable4): add missing annotations
  CHANGELOG.md
  lib/Controller/ApiController.php
Labels: bug, technical debt

#2359 fix: show expiration message again in submit view
  src/views/Submit.vue
Labels: backport-request, 3. to review, regression, feature: 📝 submitting responses

#2355 chore: remove legacy link support
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Form.php
  lib/Migration/Version050000Date20241005173955.php
  lib/Service/FormsService.php
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/views/Create.vue
  src/views/Submit.vue
Labels: 3. to review, technical debt

#2352 chore: set min NC30 and add stable4 to dependabot
  .github/dependabot.yml
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, technical debt

#2371 fix: Update transfer ownership logic
  src/components/SidebarTabs/TransferOwnership.vue
Labels: bug, javascript, backport-request, 3. to review, regression

#2353 chore: use attributes to define routes
  appinfo/routes.php
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  lib/Controller/ShareApiController.php
  src/FormsSettings.vue
Labels: 3. to review, technical debt

#2383 Update issue template to use new types
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3. to review, technical debt

#2381 Update psalm workflow from template and rename file
  .github/workflows/psalm-matrix.yml
  .github/workflows/psalm.yml
  lib/Db/Form.php
  lib/Db/Question.php
Labels: 3. to review, technical debt
