Repository nextcloud/forms, pull requests merged in 2024-12, with the labels that each got.

#2447 Fix translation problem in notifications
  lib/Activity/Provider.php
  tests/Unit/Activity/ProviderTest.php
Labels: bug, backport-request, 3. to review, language l10n and translations

#2456 chore: npm run format:fix
  playwright/support/fixtures/random-user.ts
  playwright/support/sections/QuestionSection.ts
  playwright/support/utils/session.ts
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/QRDialog.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionShort.vue
  src/components/SidebarTabs/TransferOwnership.vue
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: 3. to review, technical debt

#2465 Use pr-feedback workflow from organisation
  .github/pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, technical debt

#2466 fix: failing tests
  tests/Unit/Activity/ProviderTest.php
  tests/Unit/FormsMigratorTest.php
Labels: bug, 3. to review

#2469 Add reuse badge and template sync
  .github/workflows/reuse.yml
  README.md
Labels: 3. to review, documentation

#2474 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
