Repository nextcloud/forms, pull requests merged in 2024-06, with the labels that each got.

#2208 fix: Correctly label forms lists in the app navigation
  src/Forms.vue
Labels: bug, 3. to review

#2077 feat: Switch to PlayWright for E2E and component tests
  .gitattributes
  .github/workflows/cypress.yml
  .github/workflows/playwright.yml
  .gitignore
  cypress.config.ts
  cypress/.eslintrc.json
  cypress/e2e/create-form/create.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  playwright.config.ts
  playwright/e2e/create-empty-form.spec.ts
  playwright/start-nextcloud-server.mjs
  playwright/support/fixtures/form.ts
  playwright/support/fixtures/navigation.ts
  playwright/support/fixtures/random-user.ts
  playwright/support/sections/AppNavigationSection.ts
  playwright/support/sections/FormSection.ts
  playwright/support/setup.ts
  playwright/support/utils/session.ts
  tsconfig.json
Labels: 3. to review

#2215 fix: reformat composer.lock with prettier
  composer.lock
Labels: technical debt

#2221 Update npm and composer deps
  composer.lock
  package-lock.json
  package.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies, 3. to review, technical debt
