Repository nextcloud/forms, pull requests merged in 2024-01, with the labels that each got.

#1854 enh: Show more informative buttons when selecting CSV file location
  src/views/Results.vue
Labels: enhancement, 3. to review

#1866 refactoring: move code to separate function storeAnswersForQuestion
  lib/Controller/ApiController.php
Labels: php, backport-request, 3. to review, technical debt, feature: 📝 submitting responses

#1841 fix: Prevent race condition on unique-submission forms
  lib/Controller/ApiController.php
  lib/Db/SubmissionMapper.php
  lib/Service/SubmissionService.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: bug, backport-request, 3. to review, feature: 📝 submitting responses

#1872 chore(deps): Update `@nextcloud/moment` to 1.3.0
  package-lock.json
  package.json
Labels: bug, dependencies, 3. to review

#1881 enh: Better text contrast for form description (closes #1878)
  src/views/Create.vue
  src/views/Submit.vue
Labels: enhancement, backport-request, design, 3. to review

#1758 Added possibility to link spreadsheet for automatic submission export in multiple formats
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/psalm.yml
  appinfo/routes.php
  composer.json
  composer.lock
  docs/API.md
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Db/Form.php
  lib/Migration/Version040010Date20240122133700.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  psalm.xml
  src/views/Results.vue
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/FormsMigratorTest.php
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
  tests/stubs/oc_hooks_emitter.php
Labels: enhancement, design, 3. to review, feature: 📊 responses & statistics

#1891 enh(tests): Add initial cypress tests for frontend testing
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/.eslintrc.json
  cypress/e2e/create-form/create.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, 3. to review

#1895 stop filtering result while sharing
  src/components/SidebarTabs/SharingSearchDiv.vue
Labels: bug, javascript, backport-request, 3. to review, feature: 👥 sharing settings

#1904 fix empty content public page view
  src/FormsEmptyContent.vue
  src/emptyContent.js
Labels: bug, javascript, backport-request, design, 3. to review

#1907 Fix sharing form
  src/Forms.vue
Labels: bug, backport-request, 3. to review, feature: 👥 sharing settings

#1880 enh: Use NcDialog to confirm leaving
  src/components/TopBar.vue
  src/views/Submit.vue
Labels: enhancement, javascript, design, 3. to review, feature: 📝 submitting responses

#1910 enh: Use NcDialog for confirmation when deleting all submissions
  src/views/Results.vue
Labels: enhancement, 3. to review, feature: 📊 responses & statistics

#1911 use isMenu for Download action
  src/views/Results.vue
Labels: enhancement, 3. to review, feature: 📊 responses & statistics
