Repository nextcloud/forms, pull requests merged in 2024-07, with the labels that each got.

#2223 Drop NC27 support for dependabot
  .github/dependabot.yml
Labels: 3. to review, technical debt

#2233 Replace app icon with Material Symbols version
  img/favicon-mask.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
  img/forms-dark.svg
  img/forms.svg
  src/components/Icons/FormsIcon.vue
Labels: design, 3. to review

#2162 Add QR-Code for Share Links
  package-lock.json
  package.json
  src/components/QRDialog.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
Labels: enhancement, 3. to review, feature: 👥 sharing settings

#2225 Optimization method FormsService::canSubmit
  lib/Controller/ApiController.php
  lib/Db/SubmissionMapper.php
  lib/Migration/Version040300Date20240708163401.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  tests/Unit/Db/SubmissionMapperTest.php
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: 3. to review, performances

#2241 Bug. Question type File. When multiple types are selected, only one is used.
  lib/Service/FormsService.php
  tests/Unit/Service/FormsServiceTest.php
Labels: bug, php, 2. developing, feature: ❓ question types

#2244 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#2261 fix: ignore composer.lock in prettier
  .prettierignore
Labels: technical debt

#2195 Data source for the Analytics App
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  lib/Analytics/AnalyticsDatasource.php
  lib/AppInfo/Application.php
  lib/Listener/AnalyticsDatasourceListener.php
  psalm.xml
  tests/Unit/Analytics/AnalyticsDatasourceTest.php
  tests/stubs/oca-analytics-idatasource.php
Labels: feature: 📊 responses & statistics
