Repository nextcloud/forms, pull requests merged in 2024-04, with the labels that each got.

#2052 Drop support for NC26
  .github/dependabot.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#2029 Get only forms shared with user from database
  lib/Constants.php
  lib/Controller/ApiController.php
  lib/Db/Form.php
  lib/Db/FormMapper.php
  lib/Migration/Version040200Date20240402200139.php
  lib/Migration/Version040200Date20240402224725.php
  lib/Service/CirclesService.php
  lib/Service/FormsService.php
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Service/FormsServiceTest.php
  tests/psalm-baseline.xml
Labels: enhancement, php, 3. to review

#2059 Update dependencies
  package-lock.json
Labels: dependencies, 3. to review

#1894 Add transfer ownership unit tests
  tests/Integration/Api/ApiV2Test.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: 3. to review

#2060 fix: `legacyLink` access handling
  lib/Db/Form.php
  lib/Migration/Version040200Date20240402200139.php
Labels: bug, 3. to review

#2062 fix: don't filter expired forms in navigation
  src/Forms.vue
Labels: high, 3. to review, regression

#2066 Set lastUpdated on link/unlink file
  lib/Controller/ApiController.php
  src/views/Results.vue
Labels: bug, 3. to review

#2065 fix: remove setup() and move code to data() in Results.vue
  src/views/Results.vue
Labels: 3. to review, regression, feature: 📊 responses & statistics

#2068 fix: Move non-reactive props and composables to `setup`
  src/views/Results.vue
Labels: bug, 3. to review

#2070 fix(Form): If `permitAllUsers` is not set then no public access is granted
  lib/Db/Form.php
Labels: bug, 3. to review, regression

#2069 fix(DB): Correctly fetch shared forms
  lib/Db/FormMapper.php
  lib/Service/FormsService.php
  tests/Integration/Api/ApiV2Test.php
  tests/Integration/DB/SharedFormsTest.php
  tests/Integration/IntegrationBase.php
Labels: bug, 3. to review, regression

#2073 Fix toggle between Summary and Responses Submission overview
  src/views/Results.vue
Labels: 3. to review, regression, feature: 📊 responses & statistics

#2076 Fix fetching shared forms and return array values in ApiController.php
  lib/Controller/ApiController.php
Labels: 3. to review, regression

#2093 fix: Parse momentFormat and storageFormat
  src/components/Questions/QuestionDate.vue
Labels: backport-request, 3. to review, regression

#2096 fix(refactor): Remove duplicated code from ApiController
  lib/Controller/ApiController.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: 3. to review, technical debt

#2080 feat: Allow to limit multiple question type
  docs/DataStructure.md
  lib/Constants.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  src/components/Questions/QuestionMultiple.vue
  src/mixins/QuestionMixin.js
  src/views/Submit.vue
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, 3. to review

#2100 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
