Repository nextcloud/forms, pull requests merged in 2025-03, with the labels that each got.

#2618 fix: misaligned result button
  src/components/Results/Submission.vue
Labels: bug, design, 3. to review, regression

#2633 fix: Update QRDialog title to include escape and sanitize options
  src/components/SidebarTabs/SharingSidebarTab.vue
Labels: bug, javascript, backport-request, 3. to review

#2635 fix: parameter confusion in `update:answer` events for multiple questions
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/mixins/QuestionMultipleMixin.ts
Labels: bug, javascript, 3. to review, regression

#2641 chore: move ocp dependency to vendor-bin
  composer.json
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#2649 Fix(migration): Rename primary key of uploaded_files table
  lib/Migration/Version040300Date20240523123456.php
  lib/Migration/Version050004Date20250319180638.php
Labels: bug, php, high, backport-request, 3. to review

#2655 Fix: Handle invalid form hashes correctly
  lib/Controller/PageController.php
  src/Forms.vue
Labels: bug, backport-request, 3. to review
