Repository nextcloud/forms, pull requests merged in 2025-02, with the labels that each got.

#2542 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#2484 Tests: use nc docker functions in playwright
  package-lock.json
  package.json
  playwright/support/utils/session.ts
Labels: dependencies, 2. developing, technical debt

#2541 Chore: Refactor submission handling in Results.vue
  src/components/Results/ResultsSummary.vue
  src/views/Results.vue
Labels: javascript, backport-request, 3. to review, technical debt, feature: 📊 responses & statistics

#2553 Fix: Implement debounced input handling for AnswerInput component
  src/components/Questions/AnswerInput.vue
  src/mixins/QuestionMixin.js
Labels: bug, javascript, backport-request, 3. to review, feature: 📑 form creation

#2551 fix(migration): Replace execute() with executeQuery() and executeStatement() for improved query execution
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version020202Date20210311150843.php
Labels: php, 3. to review, technical debt

#2549 fix: Correct validationTypeMenuId to use local index instead of $attrs
  src/components/Questions/QuestionShort.vue
Labels: bug, javascript, backport-request, 3. to review

#2555 Fix(routes): Add hash requirements for frontpage routes
  lib/Constants.php
  lib/Controller/PageController.php
Labels: bug, php, 3. to review, regression

#2550 Chore(psalm): Update psalm settings and baseline
  lib/Activity/ActivityManager.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Form.php
  lib/Db/Question.php
  lib/Db/Share.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Migration/Version020202Date20210311150843.php
  lib/Migration/Version020300Date20210406114130.php
  lib/Migration/Version040200Date20240219201500.php
  lib/Service/FormsService.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: php, 3. to review, technical debt

#2575 chore(stable4): Move to min version 29
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  lib/Activity/ActivityConstants.php
  lib/Activity/ActivityManager.php
  lib/Activity/Filter.php
  lib/Activity/Provider.php
  lib/Activity/Settings/FormsActivitySettings.php
  lib/Activity/Settings/NewShare.php
  lib/Activity/Settings/NewSharedSubmission.php
  lib/Activity/Settings/NewSubmission.php
  lib/Analytics/AnalyticsDatasource.php
  lib/BackgroundJob/CleanupUploadedFilesJob.php
  lib/BackgroundJob/SyncSubmissionsWithLinkedFileJob.php
  lib/BackgroundJob/UserDeletedJob.php
  lib/Capabilities.php
  lib/Constants.php
  lib/Controller/PageController.php
  lib/Db/AnswerMapper.php
  lib/Db/FormMapper.php
  lib/Db/QuestionMapper.php
  lib/Db/SubmissionMapper.php
  lib/Db/UploadedFileMapper.php
  lib/Listener/AnalyticsDatasourceListener.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version0010Date20190000000007.php
  lib/Migration/Version010200Date20200323141300.php
  lib/Service/CirclesService.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  package-lock.json
  tests/bootstrap.php
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, technical debt

#2581 fix: remove linked file from cloned form
  lib/Controller/ApiController.php
Labels: bug, php, 3. to review, feature: 📑 form creation

#2578 Fix misaligned form elements
  src/components/Icons/IconOverlay.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionLong.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: design, 3. to review, regression

#2513 fix: Improve compatibility with Windows for uploaded files
  lib/Constants.php
  lib/Service/FormsService.php
Labels: bug, php, backport-request, 3. to review, feedback-requested

#2584 feat: replace drag icon for questions
  src/components/Icons/IconDragIndicator.vue
  src/components/Questions/Question.vue
Labels: enhancement, design, 3. to review

#2571 chore: Refactor imports to use the new component paths in Vue files
  src/Forms.vue
  src/FormsEmptyContent.vue
  src/FormsSettings.vue
  src/FormsSubmit.vue
  src/components/AppNavigationForm.vue
  src/components/ArchivedFormsModal.vue
  src/components/OptionInputDialog.vue
  src/components/PillMenu.vue
  src/components/QRDialog.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionFile.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/components/Results/Submission.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/SidebarTabs/TransferOwnership.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Sidebar.vue
  src/views/Submit.vue
Labels: javascript, 3. to review, technical debt

#2092 feat: Allow to reorder options of "checkbox" "radio" and "dropdown" question types in frontend
  package-lock.json
  package.json
  playwright/support/sections/QuestionSection.ts
  src/components/Questions/AnswerInput.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/TransitionList.vue
  src/mixins/QuestionMixin.js
  src/mixins/QuestionMultipleMixin.ts
  src/models/Entities.d.ts
  src/utils/GenRandomId.js
  tsconfig.json
Labels: enhancement, 3. to review

#2592 Chore(api): Add CORS support description to multiple endpoints
  openapi.json
Labels: 3. to review, technical debt

#2533 feat: Improve error messages for invalid submissions
  lib/Controller/ApiController.php
  lib/Service/SubmissionService.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, php, 3. to review, feedback-requested

#2594 chore: fix environment for development builds to allow vue devtools
  .env.development
  REUSE.toml
Labels: 3. to review

#2579 feat: make options draggable
  CHANGELOG.en.md
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/TransitionList.vue
  src/mixins/QuestionMultipleMixin.ts
  src/models/Entities.d.ts
Labels: enhancement, javascript, design, 3. to review

#2600 fix(32bit): pin `maennchen/zipstream-php` dependency to v2
  composer.json
  composer.lock
Labels: bug, 3. to review

#2603 fix: remove group restriction on server level
  appinfo/info.xml
Labels: bug, backport-request, 3. to review, technical debt
