Repository nextcloud/forms, pull requests merged in 2025-01, with the labels that each got.

#2475 Remove duplicate playwright entries from gitignore
  .gitignore
Labels: backport-request

#2479 feat: integration of unified search
  CHANGELOG.en.md
  css/forms.css
  lib/AppInfo/Application.php
  lib/Db/FormMapper.php
  lib/Search/FormsSearchResultEntry.php
  lib/Search/SearchProvider.php
  lib/Service/FormsService.php
Labels: enhancement, php, integration, 3. to review

#2482 test(playwright): use getContainer from @nextcloud/cypress/docker
  playwright/support/setup.ts
  playwright/support/utils/session.ts
Labels: 3. to review, technical debt

#2478 chore: remove unused access variable in hasPublicLink method
  lib/Service/FormsService.php
Labels: php, 3. to review, technical debt

#2485 fix: Check admin settings when fetching shared forms
  lib/Controller/ApiController.php
  lib/Db/FormMapper.php
  tests/Integration/Api/RespectAdminSettingsTest.php
  tests/Integration/DB/SharedFormsTest.php
  tests/Integration/IntegrationBase.php
Labels: bug, backport-request, 3. to review

#2490 feat: allow cloning archived forms
  lib/Controller/ApiController.php
  src/Forms.vue
  src/components/AppNavigationForm.vue
  src/components/ArchivedFormsModal.vue
Labels: enhancement, php, javascript, 3. to review, feature: 📑 form creation

#2501 fix: subtraction in access_enum
  lib/Migration/Version050000Date20241005173955.php
Labels: bug, php, high, 3. to review

#2502 chore: update composer and npm deps
  composer.lock
  lib/Activity/ActivityConstants.php
  lib/Activity/ActivityManager.php
  lib/Activity/Filter.php
  lib/Activity/Provider.php
  lib/Activity/Settings/FormsActivitySettings.php
  lib/Activity/Settings/NewShare.php
  lib/Activity/Settings/NewSharedSubmission.php
  lib/Activity/Settings/NewSubmission.php
  lib/Analytics/AnalyticsDatasource.php
  lib/BackgroundJob/CleanupUploadedFilesJob.php
  lib/BackgroundJob/SyncSubmissionsWithLinkedFileJob.php
  lib/BackgroundJob/UserDeletedJob.php
  lib/Capabilities.php
  lib/Constants.php
  lib/Controller/PageController.php
  lib/Db/AnswerMapper.php
  lib/Db/FormMapper.php
  lib/Db/QuestionMapper.php
  lib/Db/SubmissionMapper.php
  lib/Db/UploadedFileMapper.php
  lib/Events/FormSubmittedEvent.php
  lib/Listener/AnalyticsDatasourceListener.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version0010Date20190000000007.php
  lib/Migration/Version010200Date20200323141300.php
  lib/ResponseDefinitions.php
  lib/Service/CirclesService.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  package-lock.json
  tests/bootstrap.php
  tests/stubs/oc_hooks_emitter.php
  tests/stubs/oca-analytics-idatasource.php
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies, 3. to review

#2504 Fix: only show confirmation dialog for active forms
  src/views/Submit.vue
Labels: bug, 3. to review

#2505 chore: silence eslint warning
  src/mixins/ViewsMixin.js
Labels: 3. to review, technical debt

#2269 fix: Add brute force protection to form endpoints
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Exception/NoSuchFormException.php
  lib/Middleware/ThrottleFormAccessMiddleware.php
  tests/Integration/Api/ApiV3Test.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: bug, 3. to review

#2530 Fix: Add disabled state to PillMenu and update Results view when there are no submissions
  src/components/PillMenu.vue
  src/views/Results.vue
Labels: bug, javascript, 3. to review, feature: 📊 responses & statistics

#2534 fix: Fix spreadsheet unlinking
  src/views/Results.vue
Labels: bug, javascript, 3. to review

#2532 Fix: Show sidebar toggle in all views
  src/Forms.vue
  src/components/Results/ResultsSummary.vue
  src/components/TopBar.vue
  src/mixins/ViewsMixin.js
  src/router.js
  src/views/Results.vue
Labels: bug, javascript, backport-request, 3. to review
