Repository nextcloud/forms, pull requests merged in 2025-06, with the labels that each got.

#2771 Remove unused dependency
  package-lock.json
  package.json
Labels: dependencies, 3. to review, technical debt

#2772 fix: properly set string values in exports to escape formulas
  lib/Service/SubmissionService.php
Labels: bug, backport-request, 3. to review

#2802 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2803 chore: update workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  psalm.xml
Labels: 3. to review, technical debt
