Repository nextcloud/forms, pull requests merged in 2025-04, with the labels that each got.

#2646 feat(date): allow restrictions for dates and query date ranges
  docs/DataStructure.md
  img/event.svg
  img/today.svg
  lib/Constants.php
  lib/ResponseDefinitions.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  openapi.json
  src/components/Questions/QuestionDate.vue
  src/components/Results/Answer.vue
  src/components/Results/ResultsSummary.vue
  src/components/Results/Submission.vue
  src/models/AnswerTypes.js
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, 3. to review, feature: ❓ question types

#2674 fix: quote cell values to prevent formula evaluation
  lib/Service/SubmissionService.php
Labels: bug, php, backport-request, feature: 📊 responses & statistics

#2685 fix(validation): Update validationType handling with getter/setter and simplify change logic
  src/components/Questions/QuestionShort.vue
Labels: bug, javascript, high, 3. to review, regression

#2688 chore(QuestionDate): refactor handling of computed props
  src/components/Questions/QuestionDate.vue
Labels: javascript, 3. to review, technical debt

#2683 chore: Simplify props usage by removing unnecessary bindings in various components
  src/Forms.vue
  src/FormsSettings.vue
  src/FormsSubmit.vue
  src/components/AppNavigationForm.vue
  src/components/Questions/AnswerInput.vue
  src/components/Questions/Question.vue
  src/components/Questions/QuestionFile.vue
  src/components/Results/Submission.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/SidebarTabs/SharingShareDiv.vue
  src/components/SidebarTabs/SharingSidebarTab.vue
  src/components/SidebarTabs/TransferOwnership.vue
  src/components/TopBar.vue
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
Labels: javascript, 3. to review, technical debt

#2690 chore: update composer and npm dependencies
  composer.lock
  package-lock.json
  package.json
  playwright/support/sections/FormSection.ts
  src/components/Questions/QuestionDate.vue
  src/components/Questions/QuestionFile.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/components/Results/ResultsSummary.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/TopBar.vue
  src/mixins/ShareLinkMixin.js
  src/mixins/UserSearchMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/openapi-extractor/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies, 3. to review, technical debt

#2692 [stable4] chore: update deps and adjust code to new prettier rules
  composer.lock
  package-lock.json
  package.json
  playwright/support/sections/FormSection.ts
  src/components/Questions/QuestionFile.vue
  src/components/Questions/QuestionMultiple.vue
  src/components/Questions/QuestionShort.vue
  src/components/Results/ResultsSummary.vue
  src/components/SidebarTabs/SettingsSidebarTab.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
  src/components/TopBar.vue
  src/mixins/ShareLinkMixin.js
  src/mixins/UserSearchMixin.js
  src/mixins/ViewsMixin.js
  src/views/Create.vue
  src/views/Results.vue
  src/views/Submit.vue
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies, 3. to review, technical debt

#2691 fix: address vue warnings in console
  src/components/PillMenu.vue
  src/components/Questions/QuestionDropdown.vue
  src/components/SidebarTabs/SharingSearchDiv.vue
Labels: 3. to review, technical debt

#2703 chore: fix linting on CI
  .github/workflows/lint-php-cs.yml
  .github/workflows/reuse.yml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review

#2714 fix: Preserve intermediate changes when updating answer text
  src/components/Questions/AnswerInput.vue
Labels: bug, javascript, 3. to review

#2689 chore(QuestionMultiple): update "Other" answer handling to use v-model and add change handler
  src/components/Questions/QuestionMultiple.vue
Labels: javascript, 3. to review, technical debt

#2718 fix: only show extended label for linear scale questions
  src/components/Results/ResultsSummary.vue
Labels: bug, 3. to review

#2712 feat(time): Add time restrictions and range support
  docs/DataStructure.md
  img/clock_loader_20.svg
  img/clock_loader_80.svg
  lib/Constants.php
  lib/ResponseDefinitions.php
  lib/Service/FormsService.php
  lib/Service/SubmissionService.php
  openapi.json
  src/components/Questions/QuestionDate.vue
  src/components/Results/ResultsSummary.vue
  src/components/Results/Submission.vue
  src/models/AnswerTypes.js
  tests/Unit/Service/FormsServiceTest.php
  tests/Unit/Service/SubmissionServiceTest.php
Labels: enhancement, php, javascript, 3. to review, feature: ❓ question types
